version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  app:
    build: .
    command: wait-for mysql:3306 -t 40 -- npm start
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: nodedb
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodedb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
